name: Deploy to Hostinger
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create .env file
        run: |
          echo "APP_NAME=Laravel" > .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_TIMEZONE=Europe/Madrid" >> .env
          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=https://merceyhermes.com" >> .env
          echo "APP_LOCALE=en" >> .env
          echo "APP_FALLBACK_LOCALE=en" >> .env
          echo "APP_FAKER_LOCALE=en_US" >> .env
          echo "APP_MAINTENANCE_DRIVER=file" >> .env
          echo "PHP_CLI_SERVER_WORKERS=4" >> .env
          echo "BCRYPT_ROUNDS=12" >> .env
          echo "LOG_CHANNEL=stack" >> .env
          echo "LOG_STACK=single" >> .env
          echo "LOG_DEPRECATIONS_CHANNEL=null" >> .env
          echo "LOG_LEVEL=debug" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "SESSION_DRIVER=database" >> .env
          echo "SESSION_LIFETIME=120" >> .env
          echo "SESSION_ENCRYPT=false" >> .env
          echo "SESSION_PATH=/" >> .env
          echo "SESSION_DOMAIN=null" >> .env
          echo "BROADCAST_CONNECTION=log" >> .env
          echo "FILESYSTEM_DISK=local" >> .env
          echo "QUEUE_CONNECTION=database" >> .env
          echo "CACHE_STORE=database" >> .env
          echo "CACHE_PREFIX=" >> .env
          echo "MEMCACHED_HOST=127.0.0.1" >> .env
          echo "REDIS_CLIENT=phpredis" >> .env
          echo "REDIS_HOST=127.0.0.1" >> .env
          echo "REDIS_PASSWORD=null" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "MAIL_MAILER=smtp" >> .env
          echo "MAIL_HOST=smtp.hostinger.com" >> .env
          echo "MAIL_PORT=465" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "MAIL_ENCRYPTION=ssl" >> .env
          echo "MAIL_FROM_ADDRESS=informacion@merceyhermes.com" >> .env
          echo 'MAIL_FROM_NAME="Mercè & Hermes"' >> .env
          echo "MAINTENANCE_MODE=${{ vars.MAINTENANCE_MODE }}" >> .env
          echo "MAINTENANCE_TOKEN=${{ secrets.MAINTENANCE_TOKEN }}" >> .env

          # Verificar archivo creado
          ls -la .env

      # Paso específico solo para el .env (alta prioridad)
      - name: Deploy .env file separately
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: domains/merceyhermes.com/public_html/
          local-dir: ./
          include: |
            .env
          timeout: 600000

      # Despliegue normal de archivos principales
      - name: Deploy Core Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: domains/merceyhermes.com/public_html/
          timeout: 600000
          exclude: |
            **/.git/**
            .git/**
            .git*
            **/.github/**
            **/node_modules/**
            **/vendor/**
            tests/
            README.md
            .env.example
            .env.production
            .DS_Store

      # Despliegue de vendor
      - name: Deploy Vendor Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: domains/merceyhermes.com/public_html/vendor/
          local-dir: ./vendor/
          timeout: 600000